# Generated by Django 4.1.3 on 2023-01-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=50)),
                ('image', models.URLField(blank=True)),
            ],
        ),
    ]
