# Generated by Django 4.1.3 on 2023-01-17 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lnfapp', '0002_profile_phone_alter_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
